### ISSUE TITLE
Crash on stack layout

### ISSUE THREAD

**Issue by ldelossa** [WillPower3309/swayfx#186]
### Please fill out the following:
- **Swayfx Version:**
  - `sway -v`

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
  - This will record information about sway's activity. Please try to keep the reproduction as brief as possible and exit sway.
  - Attach the **full** file, do not truncate it.

- **Configuration File:**
  - Please try to produce with the default configuration.
  - If you cannot reproduce with the default configuration, please try to find the minimal configuration to reproduce.
  - Upload the config to a pastebin such as gist.github.com.

- **Stack Trace:**
```
#0  0x000055ea3d2bdf08 in render_containers ()
#1  0x000055ea3d2be5eb in render_container ()
#2  0x000055ea3d2be6da in render_containers_linear ()
#3  0x000055ea3d2bfe8d in output_repaint_timer_handler ()
#4  0x000055ea3d2c04d4 in handle_frame ()
#5  0x00007fe502ed8dcc in wl_signal_emit_mutable (signal=<optimized out>, data=0x55ea3f53ae70)
    at ../src/wayland-server.c:2241
        pos = 0x55ea3f6a3f38
        l = 0x55ea3f6a3f38
        cursor = {link = {prev = 0x55ea3f6a3f38, next = 0x7ffff2eccb40}, notify = 0x7fe502ed5db0 <handle_noop>}
        end = {link = {prev = 0x7ffff2eccb60, next = 0x55ea3f53afb0}, notify = 0x7fe502ed5db0 <handle_noop>}
#6  0x00007fe502e15ef8 in handle_page_flip
    (fd=<optimized out>, seq=2738072, tv_sec=46813, tv_usec=277549, crtc_id=<optimized out>, data=0x55ea3ea2f020)
    at ../backend/drm/drm.c:1549
        found = true
        conn = 0x55ea3f53ae70
        plane = <optimized out>
        present_flags = <optimized out>
        present_time = {tv_sec = 46813, tv_nsec = 277549000}
        present_event = {output = 0x55ea3f53ae70, commit_seq = 473, presented = true, when = 0x7ffff2eccbd0, seq = 2738072, refresh = 16668333, flags = 7}
#7  0x00007fe50244f010 in drmHandleEvent (fd=11, evctx=evctx@entry=0x7ffff2ecd0b0) at ../xf86drmMode.c:1060
        buffer = "\002\000\000\000 \000\000\000 \360\242>\352U\000\000ݶ\000\000-<\004\000\230\307)\000P\000\000\000\240\315\354\362\377\177\000\000\000vX\313\301\005\004l0\315\354\362\377\177\000\000\002\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\220\315\354\362\377\177\000\000p\315\354\362\377\177\000\000\020\000\000\000\000\000\000\0000\315\354\362\377\177\000\000\216aQ\002\345\177\000\000Ъ\340?\352U\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000vX\313\301\005\004l`\315\354\362\377\177\000\000\000vX\313\301\005\004l\v\000\000\000\000\000\000\000\260\260\342?\352U\000\000p\315\354\362\377\177\000\000\260\260\342?\352U\000\000\000\000\000\000\000\000\000\000\210\261"...
        len = 32
        i = 0
        e = 0x7ffff2eccc60
        vblank = 0x7ffff2eccc60
        seq = <optimized out>
        user_data = <optimized out>
#8  0x00007fe502e14f9d in handle_drm_event (fd=<optimized out>, mask=<optimized out>, data=0x55ea3ea2f020)
    at ../backend/drm/drm.c:1561
        drm = 0x55ea3ea2f020
        event = {version = 3, vblank_handler = 0x0, page_flip_handler = 0x0, page_flip_handler2 = 0x7fe502e15ca0 <handle_page_flip>, sequence_handler = 0x0}
#9  0x00007fe502eda8e2 in wl_event_loop_dispatch (loop=0x55ea3ea19100, timeout=timeout@entry=-1)
    at ../src/event-loop.c:1027
        ep = {{events = 1, data = {ptr = 0x55ea3ea31a50, fd = 1050876496, u32 = 1050876496, u64 = 94464561584720}}, {events = 4, data = {ptr = 0x55ea3fe42400, fd = 1071916032, u32 = 1071916032, u64 = 94464582624256}}, {events = 116, data = {ptr = 0x3fe16d8000000000, fd = 0, u32 = 0, u64 = 4603080690672599040}}, {events = 21994, data = {ptr = 0x7ffff2ecd1d0, fd = -219360816, u32 = 4075606480, u64 = 140737268994512}}, {events = 1, data = {ptr = 0x3fe17d8800000000, fd = 0, u32 = 0, u64 = 4603098317218381824}}, {events = 21994, data = {ptr = 0x7ffff2ecd2f0, fd = -219360528, u32 = 4075606768, u64 = 140737268994800}}, {events = 49115742, data = {ptr = 0xf2ecd1f000007fe5, fd = 32741, u32 = 32741, u64 = 175045966--Type <RET> for more, q to quit, c to continue without paging--c
80404664293}}, {events = 11640, data = {ptr = 0x7ffff2ecd210, fd = -219360752, u32 = 4075606544, u64 = 140737268994576}}, {events = 1071750552, data = {ptr = 0x74000055ea, fd = 21994, u32 = 21994, u64 = 498216228330}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 46024699, data = {ptr = 0x3fe18b0000007fe5, fd = 32741, u32 = 32741, u64 = 4603113126265651173}}, {events = 21994, data = {ptr = 0x74, fd = 116, u32 = 116, u64 = 116}}, {events = 1071365192, data = {ptr = 0x4000055ea, fd = 21994, u32 = 21994, u64 = 17179891178}}, {events = 0, data = {ptr = 0x14, fd = 20, u32 = 20, u64 = 20}}, {events = 1, data = {ptr = 0x6c00000001, fd = 1, u32 = 1, u64 = 463856467969}}, {events = 32767, data = {ptr = 0x7fe502be47fb <_int_free+1675>, fd = 46024699, u32 = 46024699, u64 = 140621570263035}}, {events = 32, data = {ptr = 0x3fdbef0000000000, fd = 0, u32 = 0, u64 = 4601534227568132096}}, {events = 0, data = {ptr = 0x55ea3fd50168, fd = 1070924136, u32 = 1070924136, u64 = 94464581632360}}, {events = 1060497440, data = {ptr = 0xf2ecd2b0000055ea, fd = 21994, u32 = 21994, u64 = 17504597505038374378}}, {events = 32767, data = {ptr = 0x6c0405c1cb587600, fd = -883395072, u32 = 3411572224, u64 = 7783352385901458944}}, {events = 1071356272, data = {ptr = 0xfffffde8000055ea, fd = 21994, u32 = 21994, u64 = 18446741771607102954}}, {events = 4294967295, data = {ptr = 0x20, fd = 32, u32 = 32, u64 = 32}}, {events = 1071356256, data = {ptr = 0x3d310acf000055ea, fd = 21994, u32 = 21994, u64 = 4409317394346956266}}, {events = 21994, data = {ptr = 0x55ea3f35e820, fd = 1060497440, u32 = 1060497440, u64 = 94464571205664}}, {events = 4075606768, data = {ptr = 0xcb58760000007fff, fd = 32767, u32 = 32767, u64 = 14652591130022019071}}, {events = 1812202945, data = {ptr = 0x3fda09b0, fd = 1071253936, u32 = 1071253936, u64 = 1071253936}}, {events = 1071560528, data = {ptr = 0x3ea19038000055ea, fd = 21994, u32 = 21994, u64 = 4513046871794537962}}, {events = 21994, data = {ptr = 0x55ea3ea19058, fd = 1050775640, u32 = 1050775640, u64 = 94464561483864}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
        has_timers = <optimized out>
#10 0x00007fe502edb125 in wl_display_run (display=0x55ea3ea19010) at ../src/wayland-server.c:1493
#11 0x000055ea3d2a8509 in main ()
```

- **Description:**
Create a stack of 3 windows. 

Make the first window in the stack a tabbed container and add another window into it. 

Move up and down the stack, SwayFX will crash when you return back to the top window in the stack (the tabbed one).

**Comment by RAR27** [comment]
I can recreate. Thanks for reporting, I'll take a look.
